Диплом<Этап 1>
SergeiBrin/java-explore-with-me pull request #5
Opened 2023-07-22 07:40 UTC by SergeiBrin

2023-07-22 07:49 UTC, SergeiBrin commented
Привет, Эркин. Вот она - первая часть диплома! :)

Извини за кучу коммитов... Опять боролся с тестами гитхаб. Они такие мутные порой 😢 
PS: В итоге пересоздал ветку и открыл новый пул реквест, а то тут стоооооолько было коммитов, что лучше такое не видеть.
 
До конца не понял, нужны ли junit тесты на этом этапе. В задании ничего по этому поводу не написано, а гитхаб пропускает, поэтому пока писать их не стал. Вот.

Жду оценочек 😃

2023-07-22 10:50 UTC, ErkinKasymaliev requested changes
привет, Сергей!
Оставил комменты

2023-07-22 10:50 UTC, ErkinKasymaliev commented on statistics/stat-client/src/main/java/ru/practicum/statclient/StatClientApplication.java
> +public class StatClientApplication {
Это здесь не нужно. stat-client просто модуль, типа пакета, тут не нужна точка входа - она в stat-service

2023-07-22 10:50 UTC, ErkinKasymaliev commented on statistics/stat-client/src/main/resources/application.properties
> +
этот файл да и resources тоже здесь не нужен

2023-07-22 10:50 UTC, ErkinKasymaliev commented on statistics/stat-dto/src/main/java/ru/practicum/statdto/dto/EndpointHitDto.java
> +public class EndpointHitDto {
здесь оставь только этот класс и ViewStatsDto, остальное удали - StatDtoApplication.java и пакет resources и test

2023-07-22 10:50 UTC, ErkinKasymaliev commented on statistics/stat-client/src/test/java/ru/practicum/statclient/StatClientApplicationTests.java
> +class StatClientApplicationTests {
в этом модуле тесты не нужны

2023-07-22 15:03 UTC, SergeiBrin commented on statistics/stat-client/src/test/java/ru/practicum/statclient/StatClientApplicationTests.java
> +class StatClientApplicationTests {
+

2023-07-22 15:26 UTC, SergeiBrin commented on statistics/stat-client/src/main/java/ru/practicum/statclient/StatClientApplication.java
> +public class StatClientApplication {
✅

2023-07-22 15:26 UTC, SergeiBrin commented on statistics/stat-client/src/main/resources/application.properties
> +
✅

2023-07-22 15:29 UTC, SergeiBrin commented on statistics/stat-dto/src/main/java/ru/practicum/statdto/dto/EndpointHitDto.java
> +public class EndpointHitDto {
✅

2023-07-22 16:00 UTC, SergeiBrin commented
Эркин, я замечания устранил + плюс вообще пока убрал тесты и базу для тестов H2. Буду добавлять это вот все тестовое по мере необходимости. Ок? 

Плюс написал текст к логам в контроллере. Вот :smile:

2023-07-23 06:33 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-07-24 18:17 UTC, merged