Диплом <Этап 3>: add private accounts and subscriptions for users
SergeiBrin/java-explore-with-me pull request #7
Opened 2023-08-13 22:40 UTC by SergeiBrin

2023-08-13 23:08 UTC, SergeiBrin commented
Привет, Эркин :smiley: Как дела? 
Вот и подходит к концу мой путь в Яндекс Практикуме. Даже немножко грустно, если честно. Это последний - 3 этап дипломной работы.

На 3 этапе я реализовал функцию подисок на пользователей. Для большей реалистичности я внедрил функцию приватных аккаунтов. Их смысл в том, что если аккаунт у пользователя приватный, то подписчику необходимо подтверждение от владельца этого аккаунта. А ещё подписчик всегда может заканселить подписку на пользователя. Вот.

Ну все, жду твоего ревью. 
И Эркин, спасибо тебе за всё :innocent:

2023-08-14 12:41 UTC, ErkinKasymaliev requested changes
привет, оставил комменты!
И еще не ту версию заархивировал, проверь этот момент

2023-08-14 12:41 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/user/model/subscription/Subscription.java
> +package ru.practicum.mainservice.user.model.subscription;
давай уберем subscription в отдельный домен на уровне с user

2023-08-14 12:41 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/config/JacksonConfig.java
> +    public Hibernate5Module hibernate5Module() {
хммм, чет мне это не нравится. Есть другие способы подтянуть данные при Lazy: например fetch join. Посмотри это

2023-08-15 18:01 UTC, ErkinKasymaliev approved these changes
привет!
Работа принята!

2023-08-30 20:42 UTC, merged